version: '3'
services:
  ui:
    build:
      context: ui
      dockerfile: Dockerfile.dev
    networks:
      - web_nw
    volumes:
      - ./ui/react-ui:/app
      - node_modules:/app/node_modules
    restart: always
  api:
    build:
      context: api
      dockerfile: Dockerfile.dev
    networks:
      - web_nw
    volumes:
      - ./api/src:/app
      - ./courses:/courses
    restart: always
  proxy:
    build:
      context: proxy
      dockerfile: Dockerfile.dev
    depends_on:
      - ui
      - api
    ports:
      - "8000:80"
    networks:
      - web_nw
    restart: always
networks:
  web_nw:
    driver: bridge
volumes:
  node_modules:
    